name: DemoNewCD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'github.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'github.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG


  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'github.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD

